### ISSUE TITLE
Default

### ISSUE THREAD

**Issue by Cobord** [morphqdd/CrabStructor#1]
It may not be useful, for the purpose here. But I tried adding another syntax where instead of field_name = "...", there would be field_names as a comma separated list and those would all use std::default for their respective types.

But there is a confusion there as I describe in the 2nd test.

**Comment by morphqdd** [comment]
Hi, this couldn't be done in this version, but I'm actively developing a new version now (https://github.com/europeDreadlyDevil/CrabStructor/tree/Update-to-v0.2.0 ). It has a different field initialization structure, but it also has a default. I will also consider the possibility to quickly initialize everything as default.

**Comment by Cobord** [comment]
But do you know the explanation for the confusion in the second test?

The test looks like it passes but rust-analyzer doesn't think it should be that way.

**Comment by morphqdd** [comment]
If I correctly understood your code and what you wanted to do, then I can say that in the first version of the library all fields need to be explicitly initialized; if this is not specified, this will lead to errors

**Comment by Cobord** [comment]
It is more of a why does this work when it says it shouldn't type of bug not an error when thought it should work bug. LSP and macros interactions being confusing. Not particularly relevant, just an oddity.
